common/roles/kubevirt/tasks/main.yml

when running playbook second time, it would be good to fetch new
changes and clean old build.

kubevirt-common: clean & update kubevirt repository

---

Vagrantfile
config.yml

To be more flexible and more user friendly
this patch adds the config file used
to configure the dev environment.
Originally the env variables were used,
but this is not a transparent way of
configuration.
@cynepco3hahue if you do not have objection please review and merge.

Add config file for Vagrantfile

---

common/roles/kubevirt/tasks/main.yml
deploy-kubernetes.yml

kubevirt-deploy.yml playbook fails on absence of golang role.

deploy-kubernetes: replace golang role, we removed it past

---

common/vars/default_vars.yml

follow up with recent changes in kubevirt repository

kubevirt-common: replace glide with dep

---

inventory

This commit adds the required configurations to run
ansible broker in openshift 3.7.
The broker can fectch apbs from openshift's internal
registery.

openshift: Configure ansible broker

---

automation/run.sh

- Fix the quoting of the trap.
The current implementation caused "$run_path" to be evaluated to
the empty string, because it occurred outside of the main function.
- Don't use "find" to copy "ansible.log", since it can cause a race where
"find" copies "ansible.log" and then finds it again in the exported
artifacts dir.

automation: Fix log collection

---

LagoInitFile.yml
deploy-with-lago.yml

- Add 10GB (sparse) disk and mount it to /var/lib/docker (needed when building
Kubevirt's containers).
- Mount 100GB disk (sparse) in /opt in the master's VM. This disk will be
used for the nfs share.
- Set "docker_dev" variable which marks "docker-storage-setup" role
which disk to use.

deploy-with-lago: Add more storage

---

inventory

Openshift 3.7 has been released, there is no need to use
the unstable repo.

Use stable Openshift release

---

.gitignore
automation/check-patch.packages
automation/check-patch.repos
automation/run.sh
deploy-openshift.yml
install-kubevirt-dev.yml
install-kubevirt-release.yml
openshift/roles/kubevirt/defaults/main.yml
openshift/roles/kubevirt/filter_plugins/kubevirt_filters.py
openshift/roles/kubevirt/meta/main.yml
openshift/roles/kubevirt/tasks/main.yml
openshift/roles/kubevirt/tasks/oc_obj_task.yml

- Split the flow into two types: dev, release.
The dev flows use the manifests from manifes/dev/* (from Kubevirt's
repo) and build the containers on the VMs.
The release flow uses kubevirt.yml, and fetches the containers from a
remote registry.
- Add a role named "kubevirt" to openshift/roles which deploys Kubevirt
using kubevirt.yml. At this moment "kubevirt.yml" is fetched from
Kubevirt's repo. Some notes about the role:
- This role will be the base for an APB.
- The role assumes that the user is already login to the
cluster.
- A path to kubevirt.yml should be supplied to the role.
- At this moment the ansible modules don't support creation of
CustomResourceDefinition, thus use 'oc' command for the task.
- "install-kubevirt-release.yml" wraps the kubevirt role, and handlers
the …

Deploy Kubevirt on openshift using kubevirt.yml

---

deploy-with-lago.yml
openshift/roles/prerequisites/tasks/main.yml

openshift: Stop updating all the packages
- It's time consuming.
- It makes the env less reproducible.
deploy-with-lago: Better condition for choosing cluster type
- Fewer lines of code
- Will save a lot of lines in ansible.log

Accelerate ci

---

automation/run.sh
control.yml
deploy-openshift.yml
deploy-with-lago.yml

Adding control.yml which includes all the steps required
for installing and testing kubevirt.
With this change, each playbook can be used on its own.

untie playbooks

---

automation/check-patch.packages
automation/run.sh
deploy-openshift.yml
deploy-with-lago.yml

lago: Explicitly specify "inventory_file" variable
In Ansible 2.4.2 the "inventory_file" variable was dropped.
We need this variable in order to let Lago dynamically update the
inventory file with the details of the VMs, thus specify it explicitly.
Use Ansible 2.4.2

Use Ansible 2.4.2 - part 1

---

deploy-openshift.yml

They backported change [1] into release-3.7 branch,
which breaks our deploy-openshift.yml playbook.
It is necessary to install python-ipaddress package to satisfy that
requirement.
[1] https://github.com/openshift/openshift-ansible/pull/7137

Adding new requirement for openshift_facts

---

README.md
install-kubevirt-on-openshift.yml
openshift/roles/kubevirt/defaults/main.yml
openshift/roles/kubevirt/tasks/main.yml
openshift/roles/kubevirt/tasks/oc_obj_task.yml

We have roles for Kubernetes which use 'kubeconfig' parameter.
And next to it we have roles for OpenShift and here we use 'kconfig' as a
name for kubeconfig parameter.
This change unite name of this parameter to be 'kubeconfig' for all
roles in this repository.

Unite name of parameter for kubeconfig in repository

---

automation/check-patch.sh

With this change, the CI will run only if a file which
doesn't end with ".md" has been changed.
closes https://github.com/kubevirt/kubevirt-ansible/issues/76

automation: Run the CI only when the code changed

---

automation/check-patch.openshift_3-7.yumrepos
automation/check-patch.openshift_3-9.yumrepos
automation/check-patch.sh
automation/check-patch.yumrepos
control.yml
playbooks/utils/configure-std-ci-repos.yml

- When $STD_CI_YUMREPOS environmet variable is defined, the VMs
will be configured with the Centos repos that std-ci mirrors.
- RPM installation from the mirrors is faster (the Jenkins slave and the
mirrors server aer in the same DC.
- It will mitigate errors which occurs when Centos' repos are not
available.
closes https://github.com/kubevirt/kubevirt-ansible/issues/82
part of https://github.com/kubevirt/kubevirt-ansible/issues/44

Use std-ci mirrors

---

inventory

oc: Don't install unneeded features
- Drop manageiq - we don't use manageiq for administrating the
cluster.
- Don't install examples  - we don't use it.
ASB: Whitelist APBs from docker hub

Inventory updates

---

playbooks/cluster/kubernetes/config.yml

Also use the same role path for role prerequisites and master.

Fix role kubernetes-node not found

---

playbooks/automation/check-patch.yml
playbooks/storage.yml
roles/storage-demo-nodeconfig/README.md
roles/storage-demo-nodeconfig/defaults/main.yml
roles/storage-demo-nodeconfig/tasks/deprovision.yml
roles/storage-demo-nodeconfig/tasks/main.yml
roles/storage-demo-nodeconfig/tasks/provision.yml
roles/storage-demo/README.md
roles/storage-demo/defaults/main.yml
roles/storage-demo/tasks/deprovision.yml
roles/storage-demo/tasks/main.yml
roles/storage-demo/tasks/provision.yml
roles/storage-demo/templates/storage-demo.yml

The storage-demo role deploys a self-contained ephemeral storage
environment consisting of a cider and ceph.  This should only be used
by developers.  All data stored will be lost when the storage-demo
statefulset is terminated.
Signed-off-by: Adam Litke <alitke@redhat.com>

[WIP] storage: Add a storage-demo role

---

roles/storage-cns/README.md
roles/storage-cns/defaults/main.yml
roles/storage-cns/tasks/deprovision.yml
roles/storage-cns/tasks/main.yml
roles/storage-cns/tasks/provision.yml
roles/storage-cns/templates/storage-cns.yml

Add a storage-cns role to connect kubevirt with existing CNS storage in
the cluster.  This role does not install CNS on a cluster.  It assumes
that CNS has been installed via one of the already supported
installation methods.
Signed-off-by: Adam Litke <alitke@redhat.com>

Add storage-cns role

---

README.md
playbooks/README.md
playbooks/selinux.yml

Currently SELinux permissive mode is required in order to run this early version of KubeVirt.
We will switch to enforcing mode once KubeVirt is more stable.

Temporary playbook to disable selinux

---

roles/kubernetes-master/tasks/main.yml
roles/kubernetes-master/templates/deploy_kubernetes.j2
roles/kubernetes-node/tasks/main.yml
roles/kubernetes-prerequisites/tasks/main.yml

* Move 'remove firewalld' task after 'stop and disable firewalld' task
* Change flag --skip-preflight-checks to --ignore-preflight-errors=all
* Change the command cp kubeconfig to scp, so it wouldn't fail
* Remove update_cache from package manager as it's not working on Fedora
* Disable epel repo for Fedora
* Fix Kubeadm join, fix #89

Fix deploy kubernetes cluster issues

---

roles/kubevirt/tasks/provision.yml

TASK [kubevirt : Create kube-system namespace] *********************************
Wednesday 28 March 2018  12:17:17 +0000 (0:00:00.425)       0:00:03.108 *******
[WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: ns.stdout != "{{ namespace }}"

role kubevirt: fixed warning about using jinja in when stmt

---

roles/cdi/tasks/provision.yml

With this change, kubevirt-ansible will not error out if the
clusterrolebinding already exist in the cluster.
https://github.com/kubevirt/kubevirt-ansible/issues/158

Fix for Issue#158: Making kubevirt-ansible more idempotent

---

roles/cdi/tasks/deprovision.yml
roles/cdi/templates/cdi-controller-deployment.yml

@aglitke @rthallisey - can you take a look, as I was testing some stuff out, I noticed that we get an error if we run `provision` on cdi role and then `deprovision` and then `provision` again...so I added removing the clusterrolebinding in the deprovision and general ignore_errors in case someone manually does this by accident.

update deprovision task to delete role

---

roles/storage-glusterfs/tasks/provision.yml
roles/storage-glusterfs/templates/storage-glusterfs.yml.j2

This PR contains two critical updates to the StorageClass created by the sotrage-glusterfs role:
* Sets the GlusterFs volume option "group virt" to enable beat-practice configurations for virtualization workloads
* Creates a separate Secret for use by the kubevirt StorageClass
Depends on #175 
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

GlusterFS: Updates to StorageClass

---

roles/storage-glusterfs/tasks/provision.yml

When grabbing the heketi route the json data is in an array.  Update the
jsonpath expression to traverse this array.
Signed-off-by: Adam Litke <alitke@redhat.com>

Fix heketi route discovery

---

requirements.yml

From some reason kubernetes-modules disappeared from ansible galaxy.
So pulling kubernetes-modules from github instead.
Fixes: #203

Install kubernetes-modules directly from github

---

automation/check-patch.openshift_3-7.mounts
automation/check-patch.openshift_3-7.packages
automation/check-patch.openshift_3-7.repos
automation/check-patch.openshift_3-7.sh
automation/check-patch.openshift_3-7.yumrepos
inventory
playbooks/README.md
stdci.yaml

KubeVirt is targeted for Kubernetes 1.9, so there is
no need to test on Openshift 3.7 that uses K8S 1.7
closes https://github.com/kubevirt/kubevirt-ansible/issues/216

Deprecate Openshit 3.7 CI

---

automation/check-patch.openshift_3-9.sh
automation/check-patch.sh

This option will make it very simple to run the automation
locally and investigate the env.
For deploying the env without cleanup:
./automation/check-patch.openshift_3-9.sh --skip-cleanup
For removing the env:
./automation/check-patch.openshift_3-9.sh --only-cleanup
The default is to cleanup the env.

Allow to run check-patch without cleanup

---

roles/cdi/README.md
roles/cdi/defaults/main.yml
roles/cdi/templates/cdi-controller-deployment.yml

Fixes: https://github.com/kubevirt/kubevirt-ansible/issues/237
@aglitke @copejon @screeley44  PTAL

update dockerhub images url

---

automation/check-patch.mounts
automation/check-patch.packages
playbooks/cluster/openshift/config.yml
playbooks/cluster/openshift/vars/3.9.yml
playbooks/generate-tests.yml
roles/generate-tests/tasks/main.yml

- Pulling the containers in parallel should reduce runtime.
- Also, use Ansible "free" strategy plugin, which allows each host to run
until the end of the play without waiting for the other hosts.
- Remove pre/post tasks, we don't use it.
- It will be faster.
- It won't fill the master's root partition.

Improve performance

---

ansible.cfg

Will reduce the number of SSH operations, thus improve
performance.

Enable pipelining in ansible.cfg

---

automation/check-patch.openshift_3-9.sh
automation/check-patch.packages
playbooks/README.md
playbooks/cluster/openshift/vars/3.9.yml

- Use "openshift-ansible-3.9.30-1" tag for deploying openshift 3.9
- Use "ansible-2.5.1-1.el7" - required by the modules mentioned above.
"v3.9.0" isn't static, and is being updated approximately once a week.
This is not the optimal solution for CI, but we need to use up to date
images.

Update openshift-ansible modules

---

roles/kubevirt/defaults/main.yml
roles/kubevirt/tasks/provision.yml
roles/kubevirt/templates/.gitignore
roles/kubevirt/templates/kubevirt.yaml.j2

This change allows kubevirt-ansible to consume a jinja2 template rather than a pre-rendered manifest from kubevirt.
For now, we include a jinja2 version, but the aim is to have upstream kubevirt maintain it. Otherwise we'll have to set up some system to automatically create a new j2 when upstream changes.
This replaces messed up PR#253

Render a jinja2 template for the kubevirt manifest

---

automation/check-patch.sh
inventory
playbooks/cluster/openshift/README.md
playbooks/provider/lago/LagoInitFile.yml.j2

- Set Openshift's router domain name to "cloudapps.example.com".
- Use static IP for Lago's VMs.
- Add a DNS recored that translates
"heketi-storage-app-storage.cloudapps.example.com" to the IP of the
node which runs Openshift's router.
-  Set "storge-glusterfs" as the default storage role
This fix has some drawbacks:
- If a different provider will be used, new code the configure/deploys a
DNS server should be added.
- The DNS entry applies only to the "heketi" service, since wildcard DNS
entries are not supported by Libvirt (which create the DNS server).
- Changes to the name of Gluster's namespace or to the router's domain
name will require a change in LagoInitFile.

Add a DNS record for heketi

---

playbooks/README.md
playbooks/cluster/openshift/config.yml
playbooks/selinux.yml

Since kubevirt/kubevirt#639 was merged, we should be able to run
kubevirt with SELinux enabled, on all cluster nodes.

Enable selinux for openshift cluster

---

roles/kubernetes-master/templates/deploy_kubernetes.j2

This PR resolves issue #15 and will mark all masters as schedulable, rather than just the first master.

fixing issue w/ kubernetes deploy script

---

roles/kubevirt/tasks/provision.yml

(cherry picked from commit 61500fc8dd66fd6f55f5fcba28de154706a6dc36)

Always use the j2 from kubevirt releases

---

playbooks/provider/lago/LagoInitFile.yml.j2

The glusterfs namespace was changed from 'app-storage'
to 'glusterfs', so the DNS record should be changed accordingly.

Update gluster DNS record

---

roles/kubevirt/tasks/provision.yml

this condition might fail if the task which registers `offline_templates` is skipped.
Typical error:
```
The conditional check 'offline_templates.stat.exists == True' failed.
The error was: error while evaluating conditional
(offline_templates.stat.exists == True): 'dict object' has no attribute
'stat'
```
The idea is to check if `offline_templates` is skipped before trying to
evaluate `offline_templates.stat.exists`
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

kubevirt: fix condition error on render offline template task

---

README.md
hack/common.sh
hack/run-tests.sh
playbooks/automation/check-patch.yml
playbooks/cluster/openshift/vars/gluster.yml
tests/cdi/cdi_suite_test.go
tests/cdi/cdi_test.go
tests/manifests/golden-pvc.yml
tests/manifests/test-vm.yml
tests/util.go

This pr rely on https://github.com/kubevirt/kubevirt/pull/980 

Add CDI e2e tests

---

stdci.yaml

Make the links posted on tested PRs point to a static HTML file that
loads much faster then Blue Ocean.

Set reporting style for STDCI to plain HTML

---

inventory

* There are options set in inventory which are defaults in
openshift-ansible repository - so no need to have them in inventory
* We don't have nfs as a part of our deployment - so no need to set nfs
options for hosted etcd storage
* Update comment about node labels

inventory-file: remove default or unused options

---

inventory
playbooks/cluster/openshift/config.yml
playbooks/cluster/openshift/vars/3.10.yml
playbooks/provider/lago/config.yml

crio is going to be the default container runtime in OC 3.11.
Let's adopt this change in order to catch bugs early as possible.
Details:
- /var/lib/containers will be used for crio persistent data.
- Set "containerized=false", since it's not supported with crio.
- Drop "pre-pull" container images, since we install using RPMs.

Use crio instead of docker

---

automation/check-patch.sh

virtctl is required by some tests, thus it should be downloaded
to the host.

Download virtctl

---

roles/cdi/tasks/provision.yml

Fixes: https://github.com/kubevirt/kubevirt-ansible/issues/362

Enable privileged containers in the security context for CDI clone

---

playbooks/cluster/openshift/config.yml

The "package" module doen't have the same optimization as the "yum:
module when installing multiple packages.
Since we are not testing on Fedora images, there is no need to also use the
"dnf" moudle.

Install packages using the native packages manager

---

roles/kubevirt/defaults/main.yml
vars/all.yml

image_pull_policy variable is required by kubevirt's manifests
(cherry picked from commit f0eb0afb18553971f68b5289aa547c6795923c4d)
```release-note
NONE
```

Adding image_pull_policy

---

automation/check-patch.sh
hack/build-tests.sh
hack/dockerized.sh
playbooks/cluster/openshift/vars/gluster.yml

- Increase Gluster's deployment timeout
- Compile with timeout
- Set trace in the compilation scripts
- Don't copy VM images to the test builder container
```release-note
None
```

Infra fixes

---

roles/cdi/tasks/provision.yml

When creating the privileged scc for CDI (to enable cloning) we need to
apply it to the namespace where CDI is installed (not always 'default').
Signed-off-by: Adam Litke <alitke@redhat.com>
Fixes #
```release-note
Fixed CDI installation by applying the privileged scc to the correct namespace.
```

cdi: Apply privileged scc to the correct namespace

---

roles/network-multus/defaults/main.yml

For upstream kubernetes, it should default to weave-net because
that is what the kubernetes-master role installs.
Fixes https://github.com/kubevirt/kubevirt-ansible/issues/401
```release-note
Changed default Multus CNI from flannel to weave-net for upstream kubernetes. It was changed to weave-net because that is the CNI kubevirt-ansible installs.
```

Change default Multus CNI from flannel to weave-net

---

playbooks/provider/lago/LagoInitFile.yml.j2

We keep adding more components to the deployment,
which cause the nodes RAM run out.
Adding 1GB of RAM to each node (except from the master which already
has 4GB). Now each node has 3GB of RAM.
```release-note
None
```

Increase Nodes RAM

---

playbooks/cluster/openshift/vars/3.10.yml
playbooks/cluster/openshift/vars/gluster.yml

Will reduce failures regard to Gluster deployment.
```release-note
None
```

Use a static version for glusterfs server image

---

playbooks/kubevirt-web-ui/README.md
playbooks/kubevirt-web-ui/inventory_example.ini
roles/kubevirt_web_ui/defaults/main.yml
roles/kubevirt_web_ui/tasks/console-config.yml
roles/kubevirt_web_ui/tasks/install.yml
roles/kubevirt_web_ui/tasks/main.yml
roles/kubevirt_web_ui/tasks/required_params.yml

**What**: If not set by the user, gather the `public_master_hostname` and `openshift_master_default_subdomain` parameters automatically
With this change, the only required attribute is the `kubevirt_web_ui_image_name` (docker image).
The values of `public_master_hostname` and `openshift_master_default_subdomain` are gathered only if not provided by the user explicitly.
These fact defaults are gathered from openshift-console deployment, assuming it's namespace and URL compositions as hardcoded within openshift-ansible. If this assumption is not met, the fallback value is empty string ("").
```release-note
The "public_master_hostname" and "openshift_master_default_subdomain" parameters of the "kubevirt-web-ui" playbook are optional now. …
```

Reduce required parameters for kubevirt-web-ui playbook

---

automation/check-patch.sh

When deprovision is run, args like `cluster` are left out.
```release-note
NONE
```

Deprovision is missing args

---

playbooks/kubevirt.yml
roles/kubevirt/tasks/deprovision.yml
roles/kubevirt/tasks/provision.yml
roles/network-multus/tasks/provision.yml

The multus playbooks were failing to run in the apb
because super login didn't occur until the kubevirt role
was run.  Move the login to the top level.
```release-note
NONE
```

Login as the super user first

---

tests/util.go

We saw some sporadic failures on CI due to timeouts.
Increase the default timeout and allow to run oc cmd with
a custom timeout.
```release-note
None
```

Increase timeout when validating oc cmd results

---

tests/tests_suite_test.go
tests/util.go

Collect the description of the requested objects type, from all
of the projects, on test failure. The following is an example of
the generated file tree:
exported-artifacts/
├── obj-desc
│   └── after
│       └── rbac_test.go-52
│           ├── default
│           │   ├── node
│           │   │   ├── lago-master
│           │   │   ├── lago-node0
│           │   │   └── lago-node1
│           │   └── pod
│           │       ├── docker-registry-1-hlwv2
│           │       ├── registry-console-1-ns4n9
│           │       ├── router-1-2mtvx
│           │       └── router-1-5srgx
│           ├── glusterfs
│           │   └── pod
│           │       ├── glusterfs-storage-x5vk5
│           │       ├── glusterfs-storage-zphsm
...
* The number in the test file name represents the line that caused …

Collect obj description on test failure

---

playbooks/kubevirt-web-ui/README.md
roles/kubevirt_web_ui/tasks/required_params.yml

The docker image:tag for kubevirt-web-ui can be either provided explicitly by
setting `kubevirt_web_ui_image_name` or
it can be newly determined automatically from the
`registry_url`, `registry_namespace`, `docker_tag` and `version`
variables, as they are supplied by `kubevirt-apb`.
**What this PR does**: support of kubevirt-apb provision flow without requiring any additional parameters
**Which issue(s) this PR fixes** *
So far just best-effort to verify via manual invocation of ansible-playbook by supplying various combinations of the registry_url, registry_namespace, docker_tag, version or kubevirt_web_ui_image_name.
Should be working from kubevirt-apb.
```release-note
NONE
```

Auto-compose of kubevirt_web_ui_image_name for kubevirt-apb flow

---

playbooks/kubevirt-web-ui/private/config.yml
roles/kubevirt_web_ui/defaults/main.yml
roles/kubevirt_web_ui/tasks/deprovision.yml
roles/kubevirt_web_ui/tasks/provision.yml
roles/kubevirt_web_ui/tasks/start.yml

**What this PR does** Adapts kubevirt-web-ui deployment for container (kubevirt-apb) environment:
Fixes #
Verified on fresh (today's) 3.11 OC in Upshift.
Unfortunately, I was not able to execute kubevirt-apb from UI, but mimicked on command-line:
```
docker run --rm -v $HOME/.kube:/opt/apb/.kube:z -u $UID \
docker.io/mareklibra/kubevirt-apb:latest provision \
--extra-vars '{"version":"0.9.3", "namespace":"kubevirt", "kubevirt_web_ui_namespace": "kubevirt-web-ui", "_apb_last_requesting_user":"admin", "_apb_plan_id":"default", "storage_role":"storage-none", "admin_user":"quicklab", …
```

Fix kubevirt-web-ui for kubevirt-apb

---

playbooks/kubevirt-web-ui/private/config.yml
roles/kubevirt_web_ui/defaults/main.yml
roles/kubevirt_web_ui/tasks/deprovision.yml
roles/kubevirt_web_ui/tasks/provision.yml
roles/kubevirt_web_ui/tasks/start.yml

Backport of #464 
Verified on fresh (today's) 3.11 OC in Upshift.
Unfortunately, I was not able to execute kubevirt-apb from UI, but mimicked on command-line:
```
docker run --rm -v $HOME/.kube:/opt/apb/.kube:z -u $UID \
docker.io/mareklibra/kubevirt-apb:release-0.9 provision \
--extra-vars '{"version":"0.9.3", "namespace":"kubevirt", "kubevirt_web_ui_namespace": "kubevirt-web-ui", "_apb_last_requesting_user":"admin", "_apb_plan_id":"default", "storage_role":"storage-none", "admin_user":"quicklab", "admin_password":"RedHat1!", "platform":"openshift", "docker_tag":"1.3", "registry_url":"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888", "registry_namespace":"cnv-tech-preview"}'
```
The `docker.io/mareklibra/kubevirt-apb:latest` is built from kubevirt-apb master using this …

[release-0.9] Fix kubevirt-web-ui for kubevirt-apb

---

tests/e2e_test.go

"PVC with invalid image url" test from e2e test is
failing even when the importer pod is failing.
The reason is that we try to assert that the pod is in Failed state,
while OC keep restarting it, so the status is Running.
```release-note
None
```

Set flaky CDI test in pending mode

---

tests/framework/util.go
tests/secrets_and_cfgmap_test.go

1) Add test, configmap and secret as volumes on
the same VM.
2) Add test, Secret with SSH Keys - Single Volume.
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>
**What this PR does / why we need it**: Adds tests related to `secrets and configmap as volumes`.
Fixes #
```
1. I am aware of this PR, which does some major `framework` related changes, https://github.com/kubevirt/kubevirt-ansible/pull/473 . Will rebase this PR once PR 473 is merged.
2. `Add test, Secret with SSH Keys - Single Volume.`, this test did not pass for me locally, but still raising this PR for any review …
```

Add tests for, secrets and configmap as volumes

---

tests/framework/cli_exec.go

Fixes #489 
```release-note
NONE
```

Removed use of duplicate namespace in RunCommand function

---

roles/network-multus/defaults/main.yml

When creating a ServiceInstance and running the APB the following error occurs:
...
TASK [network-multus : Render multus deployment yaml] **************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'registry_url' is undefined"}
...
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
name: kubevirt
namespace: kube-system
spec:
clusterServiceClassExternalName: localregistry-virtualization
clusterServicePlanExternalName: default
parameters:
admin_user: admin
admin_password: ...OUTPUT...
Besides registry_url, docker_tag and registry_namespace are also required.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …

adding missing apb params

---

tests/framework/util.go
tests/serviceaccount_test.go

1) Add test, non default serviceAccount on the VM.
2) Add test, 2 serviceAccount on the same VM should fail.
Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>
**What this PR does / why we need it**: Adds tests related to `serviceAccount as voume`.
Fixes #
```NONE
```

Add tests for, serviceAccount as volumes

---

automation/check-patch.sh
roles/kubevirt/tasks/deprovision.yml
roles/kubevirt_web_ui/tasks/required_params.yml

This PR remove the "v" character from the `set_fact: kubevirt_web_ui_image_tag`
This PR also fix the deprovision of kubevirt. when we check the kubevirt namespace
oc get ns | grep -w 'kubevirt'
kubevirt                            Active    1d
kubevirt-web-ui                     Active    1h
check the command to be 
oc get ns | grep 'kubevirt '  (space added)
Fixes #
```release-note
None
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

fix kubevirt-web-ui tag when docker_tag is configured

---

roles/kubevirt/defaults/main.yml
roles/kubevirt/tasks/provision.yml
roles/network-multus/tasks/provision.yml

This PR fix two BZ.
* https://bugzilla.redhat.com/show_bug.cgi?id=1664276
Run playbook as an unprivileged user (non-root)
* https://bugzilla.redhat.com/show_bug.cgi?id=1664274
For now I change update the timeout for the network playbook checks.
I cant find a better way right now to handle this issue
To run the playbook as an unprivileged user I just download the yaml file if required to /tmp and not to the playbook folder that need privileged.
```release-note
Run playbook as an unprivileged user (non-root)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt-ansible/541)

Change the offline template to rpm template and increase multus timeout

---

roles/kubevirt_web_ui/README.md
vars/all.yml

For consistency with the other roles.
Conforms update in the Operator code [1], released within v0.0.2 [2].
[1] https://github.com/kubevirt/web-ui-operator/pull/25
[2] https://github.com/kubevirt/web-ui-operator/releases/tag/v0.0.2
**What this PR does / why we need it**: 
In Web UI playbook, the `kubevirt_web_ui_version` parameter can be reused from the `docker_tag`, it means it's prefixed with the `v` like `v1.4.0`
Upstream build of the operator with relevant change is already published.
```release-note
NONE
```

kubevirt_web_ui_version variable is prefixed with `v`

---

roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_cr.yaml
roles/kubevirt_web_ui/tasks/main.yml
roles/kubevirt_web_ui/tasks/provision.web-ui.yml
vars/all.yml

**What this PR does / why we need it**: The Web UI playbook is blocked until initial deployment is successfully finished
When the playbook finishes, the system is already in the desired state.
The playbook fails if the desired state can not be reached.
Please do not merge this before #557 
```release-note
None
```

Web UI: Block playbook execution till deployment is finished

---

README.md
roles/kubevirt/defaults/main.yml
roles/kubevirt/tasks/deprovision.yml
roles/kubevirt/tasks/provision.yml
roles/kubevirt/templates/.gitignore
roles/kubevirt/templates/kubevirt-cr.yaml.j2
roles/kubevirt/templates/kubevirt-operator.yaml.j2
vars/all.yml

Use Ansible to orchestrate deployment while OLM continues to develop.
This PR will break CI until operator PRs merge.
```release-note
Launch kubevirt and some components as operators
```

Replace kubevirt deploy tasks with the operator

---

README.md
roles/kubevirt/defaults/main.yml
roles/kubevirt/tasks/deprovision.yml
roles/kubevirt/tasks/provision.yml
roles/kubevirt/templates/.gitignore
roles/kubevirt/templates/kubevirt-cr.yaml.j2
roles/kubevirt/templates/kubevirt-operator.yaml.j2
vars/all.yml

Use Ansible to orchestrate deployment while OLM continues to develop.
This PR will break CI until operator PRs merge:
- https://github.com/kubevirt/kubevirt/pull/1860
- https://github.com/kubevirt/kubevirt/pull/1803
- https://github.com/kubevirt/containerized-data-importer/pull/579
(cherry picked from commit 3f57e5a8e3f71ecfb784cb15e107ef084687266d)
```release-note
Install KubeVirt with an operator
```

Replace kubevirt deploy tasks with the operator (#536)

---

playbooks/kubevirt-ssp.yml
playbooks/kubevirt.yml
roles/kubevirt-ssp/README.md
roles/kubevirt-ssp/defaults/main.yml
roles/kubevirt-ssp/files/common-templates-v0.4.1.yaml
roles/kubevirt-ssp/tasks/deprovision.yml
roles/kubevirt-ssp/tasks/main.yml
roles/kubevirt-ssp/tasks/provision.yml

Add deployment of common templates using kubevirt ansible based on [templates v0.4.0](https://github.com/kubevirt/common-templates/releases/tag/v0.4.0)
The templates included here are for : cenots7, rhel7 and win2k12r2 (this is cut from the common-templates file)
This is a temporary deployment solution until we use deployment with ssp-operator (ansible operator sdk)
```release-note
deploy kubevirt templates 
```

Add templates deployment to kubevirt ansible

---

roles/kubevirt-cpu-node-labeller/tasks/deprovision.yml
roles/kubevirt-cpu-node-labeller/tasks/provision.yml
roles/kubevirt-cpu-node-labeller/templates/kubevirt-cpu-node-labeller-0.0.1.yaml

Moved cpu-node-labeller into initContainers. Added second cpu-node-labeller into containers to sleep infinity and to hold pod running (so it is not restarted again and again), because when daemonset pod finishes, it is restarted everytime it finishes (restartPolicy can't be turned off for daemonset pods).
```release-note
NONE
```

Add sleep container in cpu-node-labeller to prevent  restarting

---

tests/rbac_test.go

Something changed in kubevirt-0.13 that caused a regression test to fail.
I think this needs to be addressed in kubevirt/kubevirt.  Commenting out
the test temporarily to unblock the gate.
https://github.com/kubevirt/kubevirt-ansible/issues/575
```release-note
None
```

Comment out view test

---

roles/kubevirt-cpu-node-labeller/tasks/provision.yml

changed oc create to oc apply.
oc create throws error when user tries to run ansible twice, oc apply updates it without error
```release-note
NONE
```

changed oc create to oc apply in kubevirt-cpu-node-labeller

---

roles/cdi/templates/cdi-uploadproxy-route.yaml.j2

changed route name to cdi-uploadproxy, in order to be consistent with system naming
Fixes #
```release-note
NONE
```

change cdi-uploadproxy route name

---

tests/high_performance_vm_test.go

Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>
**What this PR does / why we need it**: Added attributes and test_ids to the high_performance_vm tests"
Fixes #
```NONE
```

Added attributes and test_ids to the high_performance_vm tests

---

roles/network-multus/tasks/deprovision.yml

**What this PR does / why we need it**: delete SR-IOV resources on deprovisioning. The only piece that is not cleaned up is /etc/pcidp because I don't know how to do it easily without running a new container that would delete the directory, on all cluster nodes, which seems like overkill.
Fixes #
```release-note
NONE
```

Deprovision sriov resources

---

roles/kubevirt_web_ui/tasks/deprovision.web-ui.yml
roles/kubevirt_web_ui/tasks/main.yml
roles/kubevirt_web_ui/tasks/provision.web-ui.yml

The deprovision.web-ui tasks reuse the provision flow by setting
desired KubeVirt Web UI version to an empty string ("").
Prior this fix, the setting was attempted to be done via set_fact
to an existing environment value. Anyway, this was incorrect due
to precedence of parameters in Ansible.
This patch fixes the bug by setting the desired version reliably.
**What this PR does / why we need it**: Fix of [BZ 1665391](https://bugzilla.redhat.com/show_bug.cgi?id=1665391) - incorrect use of set_fact of env variable
Fixes: [BZ 1665391](https://bugzilla.redhat.com/show_bug.cgi?id=1665391)
This fix is …

WebUI: fix incorrect set_fact in deprovision

---

roles/network-multus/defaults/main.yml
roles/network-multus/templates/cni-plugins.yml

Change cni-plugins image to kubevirt/cni-default-plugins
Fixes #
Upload the cni plugins image to the kubevirt organisation in quay
```release-note
None
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt-ansible/603)

Change cni-plugins image to kubevirt/cni-default-plugins

---

tests/node_eviction_test.go

Signed-off-by: Guohua Ouyang <gouyang@redhat.com>
Fixes #
```release-note
NONE
```

Revert pending test in node eviction

---

tests/network_migration_test.go
tests/networkpolicy_test.go

Due syntax error, few our tests now broken. Please approve it fix compilation error issue
**Release note:**
```release-note
NONE
```

quick-workaround: syntax error
