Vagrantfile
common/files/keys/README

@cynepco3hahue Hi I have added my vagrant file with small tweaks. I will continue to integrate the vagrant even more.
PRM

Add the vagrantfile and key folder

---

kubernetes/roles/prerequisites/tasks/main.yml

kubelet will not start if swap is on

kubernetes-deploy: make sure that swap is off

---

.gitignore
LagoInitFile.yml
deploy-openshift.yml
deploy-with-lago.yml
inventory

1. Add the ability to deploy the playbooks on Lago environment (will add READMe in the next commits).
2. Configure Service Catalog and ASB

[WIP] Adding Lago and ASB

---

automation/run.sh
deploy-openshift.yml
inventory

1. Fix "docker-storage" configuration.
2. Stop deploying Kubevirt on Openshift in the CI flow (the current flow is a bit hacky and take a lot of 
time, let's focus on the APB way).
3. Use Openshift 3.7 RC.

Improvements

---

kubernetes/roles/deploy-kubevirt/meta/main.yml
kubernetes/roles/deploy-kubevirt/tasks/main.yml
kubernetes/roles/deploy-kubevirt/vars/main.yml
requirements.yml

- Rolls out kubevirt manifests based on variables
- Waits for rollout of DaemonSets and Deployments
Role pulled from repo: https://github.com/jcpowermac/ansible-kubevirt
where I have been doing my testing.

Deploy Kubevirt updates

---

automation/check-patch.yaml

- It will make the job run faster.
- It will allow to run nested VMs.

automation: Run CI on bare metal slaves

---

install-kubevirt-release.yml
openshift/roles/kubevirt/filter_plugins/kubevirt_filters.py

plus fixed pep8 complains in kubevirt_filter

install-kubevirt-release: replace lago-master hostvar with master

---

ansible.cfg

Will help to understand where we should improve performance.

Adding a profiler for Ansible

---

README.md
openshift/roles/kubevirt/tasks/main.yml

kubevirt-controller
kubevirt-infra
Update readme

kubevirt-on-openshift: make kubevirt service accounts privileged

---

control.yml
deploy-openshift.yml
openshift/roles/kubevirt/tasks/main.yml

Align with ansible 2.4.2 compatibility

---

inventory

Will accelerate the deployment process.
closes https://github.com/kubevirt-incubator/kubevirt-ansible/issues/41

openshift: Use containerized deployment

---

CONTRIBUTING.md

Initial contributing doc, to include relevant documentation for roles, tests, etc..
Signed-off-by: Eyal Edri <eedri@redhat.com>

[WIP] Add initial contributing document for kubevirt-ansible

---

automation/check-patch.sh
control.yml
playbooks/automation/check-patch.yml

Rename control.yml to check-patch.yml and move it into
playbooks/automation.

re-org: mv control.yml

---

README.md

re-org: Fix readme to reflect re-org changes

---

README.md

Update Readme to follow re-org and playbooks renaming

---

README.md

readme: fix link to docker-storage-defaults and example

---

playbooks/cluster/openshift/config.yml

Only enable epel for CentOS and RedHat

---

playbooks/cluster/openshift/config.yml
roles/kubernetes-master/tasks/main.yml
roles/kubernetes-prerequisites/tasks/main.yml

Change pkg manager from yum to package

---

playbooks/cluster/openshift/config.yml

Add kubeconfig path for oc configure command

---

playbooks/README.md

Caused by too quick merge of PR #114.

Fix regression in playbooks/README.md

---

playbooks/provider/lago/LagoInitFile.yml
playbooks/provider/lago/config.yml

automation: adding disk for gluster storage

---

README.md
playbooks/README.md

Document logging into an OpenShift cluster and location of kubectl config

---

README.md
vars/all.yml

Add openshift_playbook_path to top level variables file

---

playbooks/cdi.yml
playbooks/storage.yml
roles/cdi/README.md
roles/cdi/defaults/main.yml
roles/cdi/tasks/deprovision.yml
roles/cdi/tasks/main.yml
roles/cdi/tasks/provision.yml
roles/cdi/templates/cdi-controller-deployment.yml

Adding cdi provision role to kubevirt

---

playbooks/cluster/openshift/config.yml
roles/kubernetes-prerequisites/tasks/main.yml

Don't remove NM as issue #52 says.

Keep NetworkManager installed :bug:

---

roles/cdi/README.md
roles/cdi/defaults/main.yml
roles/cdi/tasks/deprovision.yml
roles/cdi/tasks/provision.yml
roles/cdi/templates/cdi-resourcequota.yml

Found that cdi needed some extra permissions  @aglitke

Update cdi role with rbac for namespace

---

playbooks/README.md

REDAME: clear our section about docker storage

---

roles/kubernetes-prerequisites/tasks/main.yml

Fix task of remove firewalld package

---

automation/check-patch.sh
playbooks/cluster/openshift/README.md
playbooks/cluster/openshift/config.yml
vars/README.md
vars/all.yml

I am not sure if this is good name, feel free to suggest other one.
But it solves issue with deploying OpenShift Enterprise.
Fixing #163 

Rename openshift_version to kubevirt_openshift_version

---

roles/storage-cns/README.md
roles/storage-cns/defaults/main.yml
roles/storage-cns/tasks/deprovision.yml
roles/storage-cns/tasks/provision.yml
roles/storage-cns/templates/storage-cns.yml

- Make deprovision idempotent
- Dynamically generate heketi rest url from cluster route

Storage cns fixes

---

roles/storage-glusterfs/README.md
roles/storage-glusterfs/defaults/main.yml
roles/storage-glusterfs/files/glusterfile-provisioner.yml
roles/storage-glusterfs/tasks/deprovision.yml
roles/storage-glusterfs/tasks/provision.yml
roles/storage-glusterfs/templates/storage-glusterfs.yml.j2

storage-glusterfs: Add support for external provisioner

---

inventory
playbooks/README.md
playbooks/cluster/openshift/README.md
playbooks/cluster/openshift/config.yml
playbooks/cluster/openshift/vars/gluster.yml
playbooks/provider/lago/LagoInitFile-glusterfs.yml
playbooks/provider/lago/LagoInitFile.yml
playbooks/provider/lago/config.yml
roles/kubevirt/README.md
vars/README.md

This is a continuation of #130, which includes its changes plus additions on my part. It is intended to supersede the original PR.

Add GlusterFS support to main deployment

---

roles/kubevirt/README.md
roles/kubevirt/defaults/main.yml
vars/README.md
vars/all.yml

Bump up KubeVirt version to new release 0.4.1

---

playbooks/README.md

Fix wrong link and add details on SELinux issue in Readme

---

roles/storage-glusterfs/tasks/deprovision.yml

Fix deprovision after provision changes.
https://github.com/kubevirt/kubevirt-ansible/pull/190

Fix deprovision for glusterfs after recent changes

---

roles/kubevirt/tasks/provision.yml

Allow a user to provide the default vm templates

---

automation/README.md
playbooks/README.md
playbooks/provider/lago/LagoInitFile-glusterfs.yml
playbooks/provider/lago/LagoInitFile.yml

Update VM images to Centos 7.5

---

roles/cdi/tasks/deprovision.yml
roles/cdi/tasks/provision.yml
roles/cdi/templates/cdi-controller-deployment.yml

update role with tighter svcacct rules

---

roles/cdi/templates/cdi-controller-deployment.yml

Fixes https://github.com/kubevirt/kubevirt-ansible/issues/238
@aglitke @screeley44

add ClusterRole secret to cdi-controller-deployment

---

automation/README.md
playbooks/README.md

fix automation/README.md wrong link

---

roles/kubevirt/README.md
roles/kubevirt/defaults/main.yml

Update kubevirt version on all places in repository

---

inventory

inventory: Enabling KubeVirt Admission Controller

---

roles/storage-demo-nodeconfig/tasks/provision.yml

fixes: https://github.com/kubevirt/kubevirt-ansible/issues/221

Iptables changes need root

---

roles/kubevirt/README.md
roles/storage-demo/README.md
roles/storage-glusterfs/README.md

docs enhance: add usage command

---

roles/storage-demo/defaults/main.yml
roles/storage-demo/templates/storage-demo.yml

Fixes: https://github.com/kubevirt/kubevirt-ansible/issues/250
@gbenhaim @rthallisey @aglitke @copejon PTAL

move secret file to the right namespace

---

automation/README.md

Dependent on https://github.com/kubevirt/kubevirt-ansible/pull/255

Explain how to run the automation locally

---

automation/check-patch.sh

check-patch: Print Ansible version

---

roles/storage-demo-nodeconfig/tasks/deprovision.yml

Deprovision needs permission to remove iptables rules

---

roles/kubevirt/defaults/main.yml
roles/kubevirt/tasks/deprovision.yml
roles/kubevirt/tasks/provision.yml

Add privileged role to kubevirt-apiserver security context

---

roles/storage-demo/templates/storage-demo.yml

Fixes: https://github.com/kubevirt/kubevirt-ansible/issues/232
@aglitke @qwang1 @gouyang PTAL, not sure if this is a corret way to fix it, but the root cause I guess is already as @qwang1 described

fix kraken crash due to MON_IP with wrong value

---

glide.yaml
hack/run-tests.sh
roles/kubevirt/README.md
roles/kubevirt/defaults/main.yml
vars/README.md
vars/all.yml

Bump up to new release of kubevirt 0.6.0

---

playbooks/storage.yml

Fixes https://github.com/kubevirt/kubevirt-ansible/issues/298

remove cdi role from playbooks/storage.yml

---

roles/cdi/templates/cdi-controller-deployment.yml

Fixes https://github.com/kubevirt/kubevirt-ansible/issues/284

add cdi datavolumes and events to clusterroles

---

playbooks/README.md

Encourage the user to report issue instead of silently disable the source of issue (selinux).

Add proposal to create issue for kubevirt

---

automation/check-patch.openshift_3-10.mounts
automation/check-patch.openshift_3-10.packages
automation/check-patch.openshift_3-10.repos
automation/check-patch.openshift_3-10.sh
automation/check-patch.openshift_3-10.yumrepos
inventory
playbooks/cluster/openshift/config.yml
playbooks/cluster/openshift/vars/3.10.yml
playbooks/cluster/openshift/vars/3.7.yml
playbooks/provider/lago/config.yml
stdci.yaml

And removing unneeded Openshift 3.7 file

Adding Openshift 3.10 CI

---

automation/check-patch.sh

When running deprovision the logs of KubeVirt's containers
are removed. Add log collection before deprovision for debug purposes.

Collect logs before running deprovision

---

roles/kubevirt/tasks/deprovision.yml
roles/kubevirt/tasks/provision.yml

kubevirt role: deploy presets from demo-content.yaml

---

automation/check-patch.packages
playbooks/README.md

Update Ansible version to 2.6.1-1

---

roles/kubevirt/tasks/deprovision.yml

kubevirt-deprovision ignore when presets are not found

---

tests/cdi/cdi_suite_test.go
tests/cdi/cdi_test.go
tests/util.go

@aglitke @jeffvance @copejon PTAL

CDI  add negative tests and refactor util functions

---

glide.lock
glide.yaml
hack/common.sh
hack/run-tests.sh
tests/cdi/cdi_suite_test.go
tests/network_connectivity_test.go
tests/test.go
tests/tests_suite_test.go
vendor/kubevirt.io/qe-tools/.gitattributes
vendor/kubevirt.io/qe-tools/.gitignore
vendor/kubevirt.io/qe-tools/.travis.yml
vendor/kubevirt.io/qe-tools/LICENSE
vendor/kubevirt.io/qe-tools/Makefile
vendor/kubevirt.io/qe-tools/glide.lock
vendor/kubevirt.io/qe-tools/glide.yaml
vendor/kubevirt.io/qe-tools/hack/dep-prune.sh
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
vendor/kubevirt.io/qe-tools/pkg/polarion-generator/README.md
vendor/kubevirt.io/qe-tools/pkg/polarion-generator/test_cases_generator.go
vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go

Add option to pass additional arguments to test execution,
it will be useful on our environment when we want to generate junit
results for example.

run-tests.sh: add FUNC_TEST_ARGS param

---

tests/cdi/cdi_suite_test.go
tests/cdi/cdi_test.go
tests/util.go

add JustBeforeEach to CDI tests

---

automation/check-patch.sh
playbooks/automation/check-patch.yml
playbooks/generate-tests.yml
roles/generate-tests/defaults/main.yml
roles/generate-tests/tasks/main.yml

Will reduce runtime by ~6 minutes

Compile tests in the background

---

playbooks/provider/lago/LagoInitFile.yml.j2
playbooks/provider/lago/config.yml
playbooks/provider/lago/defaults/main.yml

Store the VM image type in a variables file.

Use variable file for lago provider

---

hack/run-tests.sh

run-tests.sh: make paths to binaries configurable

---

automation/check-patch.sh

- Run in /dev/shm only if it has 30GB of free space (15 GB isn't enough).
- Print resource usage on the host - will help to debug disk space
issues.

Increase memory requirements and improve logging

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

* Provide a structured entrypoint when creating Issues or PRs
* Describe basic prow interaction (/kind and release-note)

Add Issue and Pull Request templates for github

---

tests/e2e_test.go

Fixes #
```release-note
NONE
```

e2e-tests: move e2e tests to proper package

---

tests/manifests/import-vm-v2v-apb.yml
tests/v2v_test.go

[RFR] Added v2v tests

---

tests/rbac_test.go
tests/util.go

RBAC Authorization tests for subresource API with:
Default Admin role.
Default Edit role.
Default View role.
https://trello.com/c/MQjYEozE/121-epic-authorization-install-openshift-policies-for-kubevirt-api

[RFR] RBAC testing.

---

roles/cdi/README.md
roles/cdi/defaults/main.yml
roles/storage-demo/defaults/main.yml

Fixes #
```release-note
NONE
```

change cdi_namespace from golden-images to kube-system

---

roles/kubernetes-master/templates/deploy_kubernetes.j2

Signed-off-by: karmab <karimboumedhel@gmail.com>

Allow masters to run pods with a simpler command

---

roles/kubevirt/tasks/provision.yml

Signed-off-by: karmab <karimboumedhel@gmail.com>

Ignore crd validations to run on latest k8s

---

roles/kubevirt/tasks/provision.yml
roles/kubevirt/templates/.gitignore
roles/kubevirt/templates/kubevirt-config.yaml

Add the feature gate config to deployment.  Default it to enable DataVolumes.
```release-note
NONE
```

Add kubevirt feature gate config

---

playbooks/kubevirt-web-ui/README.md
roles/kubevirt/tasks/provision.yml
roles/kubevirt/templates/.gitignore
roles/kubevirt/templates/kubevirt-config.yaml
roles/kubevirt_web_ui/tasks/required_params.yml

backport 927e5c8185baf4b431720e76398e42bd84198be8 and b24d23059a7d6d0cf1054f486bb71a09942b3e5c
```release-note
None
```

Backport 24fc8ed9 927e5c818

---

tests/util.go

[VIRT] Fix sidecar expector

---

tests/rbac_test.go
tests/util.go

This PR will fix the issue that may cause by the common failure of RBAC test.  
**Which issue(s) this PR fixes** 
Fixes #447
```release-note
NONE
```

RBAC tests update with error handling

---

tests/e2e_test.go
tests/manifests/golden-pvc.yml

Fixes https://github.com/kubevirt/kubevirt-ansible/issues/428
```release-note
bump CDI version to 1.3.0
```

Fix CDI 1.3 importer pod deletion logic change 

---

CONTRIBUTING.md
playbooks/README.md
roles/kubevirt/README.md

Fixes #506 
```release-note
NONE
```

fix: invalid urls and typos 

---

playbooks/README.md

Fixes #
```release-note
NONE
```

Some clarifications and fixes for playbooks/ README

---

playbooks/network.yml

Bug fix
Fixes #477 
```release-note
NONE
```

remove multus conf on deprovision

---

playbooks/kubevirt.yml
roles/network-multus/templates/sriovdp.yml

Fixes #
```release-note
NONE
```

Remove spc_t for sriovdp

---

README.md

Fixes none
@gbenhaim 
```release-note
NONE
```

readme: fix kubernetes/kubevirt typo

---

automation/check-patch.sh
roles/skydive/defaults/main.yml
roles/skydive/templates/kubernetes-skydive.yaml
roles/skydive/templates/openshift-skydive.yaml

Support cri-o engine for the skydive deployment
Fixes #
```release-note
Support cri-o engine in skydive.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt-ansible/529)

Allow runc on the skydive deployment.

---

roles/kubevirt/templates/kubevirt-config.yaml

LiveMigration,CPUManager
Fixes #
```release-note
```

Add feature gates to kubevirt-config

---

tests/templates_verification_test.go

This test case checks if common-templates.yaml is valid for UI or not.

add templates test verification testcase

---

tests/framework/cli_exec.go
tests/framework/util.go

Fixes #
```release-note
NONE
```

remove namespace duplication

---

roles/kubevirt_web_ui/README.md
roles/kubevirt_web_ui/files/crds/kubevirt_v1alpha1_kwebui_cr.yaml
roles/kubevirt_web_ui/tasks/main.yml
roles/kubevirt_web_ui/tasks/provision.web-ui.yml
vars/all.yml

**What this PR does / why we need it**: Backport of #558 & #557 
Fixes #
I hope this will not cause merge conflict with #565.
@rthallisey , If you prefer simplicity over consistency, this includes the #565 already.
If merged here and only, the #565 can be freely abandoned.
```release-note
none
```

Backport: Web UI: Block playbook execution

---

roles/kubevirt/templates/kubevirt-config.yaml

Limit features gates.
```release-note
None
```

Limit the feature gates to SRIOV and DataVolumes in 0.12.0

---

playbooks/kubevirt-cpu-node-labeller.yml
playbooks/kubevirt.yml
roles/kubevirt-cpu-node-labeller/README.md
roles/kubevirt-cpu-node-labeller/defaults/main.yml
roles/kubevirt-cpu-node-labeller/tasks/deprovision.yml
roles/kubevirt-cpu-node-labeller/tasks/main.yaml
roles/kubevirt-cpu-node-labeller/tasks/provision.yml
roles/kubevirt-cpu-node-labeller/templates/kubevirt-cpu-node-labeller-0.0.1.yaml

(cherry picked from commit 207f58372c913b47d30b1b946cd3b114a664502b)
```release-note
None
```

Add kubevirt-cpu-node-labeller deployment to kubevirt ansible

---

roles/cdi/tasks/deprovision.yml
roles/cdi/tasks/provision.yml
roles/cdi/templates/cdi-uploadproxy-route.yaml.j2

Fixes #
```release-note
Added Openshift Route to expose CDI Upload Proxy service
```

Expose CDI Upload Proxy service

---

roles/cdi/tasks/deprovision.yml
roles/cdi/tasks/provision.yml
roles/cdi/templates/cdi-uploadproxy-route.yaml.j2
roles/kubevirt-cpu-node-labeller/tasks/deprovision.yml
roles/kubevirt-cpu-node-labeller/tasks/provision.yml
roles/kubevirt-cpu-node-labeller/templates/kubevirt-cpu-node-labeller-0.0.1.yaml
tests/rbac_test.go

backports 3c0fe156f8b27966befa6d08e4bd020da81c7eca 7c0b1216b58f3e81f0d497c7482b00c43df77748 9a9a2b7f5939a2b4ce39770ec2b6004fe6491cf2
```release-note
None
```

3 backports

---

roles/kubevirt-cpu-node-labeller/tasks/provision.yml

(cherry picked from commit c5d34db351b6b60958d6170faedfe5cc6d300180)
```release-note
None
```

changed oc create to oc apply in kubevirt-cpu-node-labeller (#585)

---

tests/secrets_and_cfgmap_test.go

Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>
**What this PR does / why we need it**: `Adds test attributes to secrets_and_cfgmap_test`
Fixes #
```
NONE
```

Adds test attributes to secrets_and_cfgmap_test

---

tests/framework/util.go
tests/manifests/ovs-vlan-net.yml
tests/manifests/privileged-pod.yml
tests/network_connectivity_test.go

Add test for Multus and OVS CNI.
Create VMs with OVS network via Multus and check connectivity.

[Tests] Add test for Multus and OVS CNI

---

vars/all.yml

To 1.4.0-13
Reflects KubeVirt API version change.
Fixes #
```release-note
NONE
```

Bump kubevirt-web-ui version

---

tests/framework/util.go
tests/manifests/privileged-pod.yml
tests/network_connectivity_test.go
vendor/kubevirt.io/kubevirt/tests/utils.go

Test that VLAN interface can't ping non VLAN interface.
Test that when VMI is deleted the veth interfaces are deleted as well from the node.
```release-note
NONE
```

VLAN to no VLAN connectivity and veth leftovers tests

---

automation/check-patch.packages
automation/check-patch.repos

Fixes #
```release-note
NONE
```

use ansible 2.7.7

---

automation/check-patch.packages

Fixes #
```release-note
None
```

make pip available

---

tests/manifests/ovs-nets.yml
tests/network_connectivity_test.go

Test connectivity between 2 VMs when VM interface is on top of OVS bridge with BOND port.
```release-note
NONE
```

Tests add multus bond

---

playbooks/network.yml
roles/skydive/README.md

It is better to use bool type for the vars (deploy_sriov_plugin & deploy_skydive) instead of string type in conditional statements
Fixes #
```release-note
NONE
```

Fix the vars to bool type and update the skydive doc

---

tests/manifests/networkpolicy-allow-http.yml
tests/manifests/networkpolicy-deny-all.yml
tests/networkpolicy_test.go

Add networkpolicy test:Set connectivity to only allow from http
Fixes #
```release-note
NONE
```

Add networkpolicy test:Set connectivity to only allow from http

---

tests/network_migration_test.go

Add test for migration masquerade vm
Fixes #
```release-note
none
```

Add test for migration masquerade vm
